language: node_js

node_js: "10.15.3"

before_script: npm i

jobs:
  include:
    - stage: lint
      name: lint
      script:
        - npm run lint

    - stage: test
      name: test
      script: npm run test

    - stage: deploy demo
      name: deploy demo
      if: branch = master AND tag IS present
      script: npm run demo:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: dist
        on:
          branch: master
          tags: true

    - stage: npm release
      name: npm release
      if: branch = master AND tag IS present
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true
